### ISSUE TITLE
MAC_DIR wrong on Mojave

### ISSUE THREAD

**Issue by AnsonT** [MikeKovarik/cert-store#1]
The correct path on Mojave is 
const MAC_DIR = '/Library/Keychains/System.keychain'

**Comment by MikeKovarik** [comment]
Hi. thanks for letting me know. I don't have any mac machine near me to test this out so i just followed google and hoped someone would come along.

Do you know if this is a new thing to just Mojave or if it applies to High Sierra as well? I'd like to support both.
